name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify your Java version
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          JENKINS_JOB_NAME="Insured_Assurance"  # Replace with your Jenkins job name
          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB_NAME/build" \
            --user "$JENKINS_USER:$JENKINS_TOKEN"
